package io.helidon.atp.mybatis.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

import io.helidon.atp.mybatis.entity.Manager;
import io.helidon.atp.mybatis.entity.ManagerExample;

@Mapper
public interface ManagerMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table MANAGER
	 *
	 * @mbg.generated Mon May 13 15:55:50 CST 2019
	 */
	long countByExample(ManagerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table MANAGER
	 *
	 * @mbg.generated Mon May 13 15:55:50 CST 2019
	 */
	int deleteByExample(ManagerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table MANAGER
	 *
	 * @mbg.generated Mon May 13 15:55:50 CST 2019
	 */
	int insert(Manager record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table MANAGER
	 *
	 * @mbg.generated Mon May 13 15:55:50 CST 2019
	 */
	int insertSelective(Manager record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table MANAGER
	 *
	 * @mbg.generated Mon May 13 15:55:50 CST 2019
	 */
	List<Manager> selectByExample(ManagerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table MANAGER
	 *
	 * @mbg.generated Mon May 13 15:55:50 CST 2019
	 */
	int updateByExampleSelective(@Param("record") Manager record, @Param("example") ManagerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table MANAGER
	 *
	 * @mbg.generated Mon May 13 15:55:50 CST 2019
	 */
	int updateByExample(@Param("record") Manager record, @Param("example") ManagerExample example);
}